//! Conversion from arkworks 0.5 into the byte layout `groth16-solana` accepts.
//!
//! Verified by execution against the pinned versions; see
//! `docs/GROTH16_INTEGRATION.md` for the evidence and the full pitfall list. The
//! three that matter here:
//!
//! * **G2 stores `c1` before `c0`.** The syscall reads
//!   `x.c1 ‖ x.c0 ‖ y.c1 ‖ y.c0`, while arkworks serialises `Fq2` as
//!   `c0 ‖ c1`. Getting this backwards produces a proof that fails to verify
//!   with no diagnostic.
//! * **`proof_a` must be negated.** The verifier computes
//!   `e(A,B)·e(Σic,γ)·e(C,δ)·e(α,β) == 1`, which holds only for `A = −A_proof`.
//!   Nothing negates it downstream.
//! * **Serialise coordinates, never the point.** arkworks packs a y-sign flag
//!   into the top bit of y's most significant byte even uncompressed, on roughly
//!   half of all points. Verification tolerates it, but the bytes are
//!   non-canonical, which silently breaks anything that hashes or compares them
//!   — including a verifying-key commitment.

use ark_bn254::{Bn254, Fq, Fr, G1Affine, G2Affine};
use ark_ec::AffineRepr;
use ark_ff::{BigInteger, PrimeField};
use ark_groth16::{Proof, VerifyingKey};

fn fq_to_be(f: &Fq) -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(&f.into_bigint().to_bytes_be());
    out
}

/// A canonical field element as the on-chain verifier expects it.
pub fn fr_to_be(f: &Fr) -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(&f.into_bigint().to_bytes_be());
    out
}

/// G1 as `x_be ‖ y_be`. The point at infinity encodes as all zeros.
pub fn g1_to_solana(p: &G1Affine) -> [u8; 64] {
    let mut out = [0u8; 64];
    if p.infinity {
        return out;
    }
    out[..32].copy_from_slice(&fq_to_be(&p.x));
    out[32..].copy_from_slice(&fq_to_be(&p.y));
    out
}

/// G2 as `x.c1_be ‖ x.c0_be ‖ y.c1_be ‖ y.c0_be` — note the cross order.
pub fn g2_to_solana(p: &G2Affine) -> [u8; 128] {
    let mut out = [0u8; 128];
    if p.infinity {
        return out;
    }
    out[..32].copy_from_slice(&fq_to_be(&p.x.c1));
    out[32..64].copy_from_slice(&fq_to_be(&p.x.c0));
    out[64..96].copy_from_slice(&fq_to_be(&p.y.c1));
    out[96..].copy_from_slice(&fq_to_be(&p.y.c0));
    out
}

/// The proof in on-chain layout. `proof_a` comes back **negated**.
pub fn proof_to_solana(proof: &Proof<Bn254>) -> ([u8; 64], [u8; 128], [u8; 64]) {
    let neg_a: G1Affine = (-proof.a.into_group()).into();
    (
        g1_to_solana(&neg_a),
        g2_to_solana(&proof.b),
        g1_to_solana(&proof.c),
    )
}

/// A verifying key in the layout `groth16_solana::groth16::Groth16Verifyingkey`
/// borrows from. `ic` has one more entry than there are public inputs.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SolanaVerifyingKey {
    pub alpha_g1: [u8; 64],
    pub beta_g2: [u8; 128],
    pub gamma_g2: [u8; 128],
    pub delta_g2: [u8; 128],
    pub ic: Vec<[u8; 64]>,
}

impl SolanaVerifyingKey {
    /// Number of public inputs this key verifies.
    pub fn public_input_count(&self) -> usize {
        self.ic.len().saturating_sub(1)
    }

    /// A stable digest over the whole key, in a fixed order.
    ///
    /// This is what a setup transcript must bind. A competing submission's
    /// ceremony verifier checks only `delta`, so it will happily certify a
    /// transcript whose verifying key belongs to an entirely different circuit.
    pub fn digest_preimage(&self) -> Vec<u8> {
        let mut buf = Vec::with_capacity(64 + 128 * 3 + self.ic.len() * 64 + 8);
        buf.extend_from_slice(&self.alpha_g1);
        buf.extend_from_slice(&self.beta_g2);
        buf.extend_from_slice(&self.gamma_g2);
        buf.extend_from_slice(&self.delta_g2);
        buf.extend_from_slice(&(self.ic.len() as u64).to_be_bytes());
        for point in &self.ic {
            buf.extend_from_slice(point);
        }
        buf
    }
}

pub fn vk_to_solana(vk: &VerifyingKey<Bn254>) -> SolanaVerifyingKey {
    SolanaVerifyingKey {
        alpha_g1: g1_to_solana(&vk.alpha_g1),
        beta_g2: g2_to_solana(&vk.beta_g2),
        gamma_g2: g2_to_solana(&vk.gamma_g2),
        delta_g2: g2_to_solana(&vk.delta_g2),
        ic: vk.gamma_abc_g1.iter().map(g1_to_solana).collect(),
    }
}

/// Renders the key as a Rust source constant for the on-chain program.
pub fn vk_to_rust_source(vk: &SolanaVerifyingKey) -> String {
    use core::fmt::Write;
    let mut s = String::new();
    let _ = writeln!(
        s,
        "//! Generated by `mirror setup`. Do not edit.\n\
         //!\n\
         //! Verifies {} public inputs: root, nullifier, action_binding.\n",
        vk.public_input_count()
    );
    let _ = writeln!(s, "use groth16_solana::groth16::Groth16Verifyingkey;\n");
    let emit = |s: &mut String, name: &str, bytes: &[u8]| {
        let _ = writeln!(s, "pub const {name}: [u8; {}] = [", bytes.len());
        for chunk in bytes.chunks(12) {
            let line: Vec<String> = chunk.iter().map(|b| format!("{b}")).collect();
            let _ = writeln!(s, "    {},", line.join(", "));
        }
        let _ = writeln!(s, "];\n");
    };
    emit(&mut s, "VK_ALPHA_G1", &vk.alpha_g1);
    emit(&mut s, "VK_BETA_G2", &vk.beta_g2);
    emit(&mut s, "VK_GAMMA_G2", &vk.gamma_g2);
    emit(&mut s, "VK_DELTA_G2", &vk.delta_g2);
    let _ = writeln!(s, "pub const VK_IC: [[u8; 64]; {}] = [", vk.ic.len());
    for point in &vk.ic {
        let _ = writeln!(s, "    [");
        for chunk in point.chunks(12) {
            let line: Vec<String> = chunk.iter().map(|b| format!("{b}")).collect();
            let _ = writeln!(s, "        {},", line.join(", "));
        }
        let _ = writeln!(s, "    ],");
    }
    let _ = writeln!(s, "];\n");
    let _ = writeln!(
        s,
        "pub const VERIFYING_KEY: Groth16Verifyingkey<'static> = Groth16Verifyingkey {{\n\
         \x20   nr_pubinputs: {},\n\
         \x20   vk_alpha_g1: VK_ALPHA_G1,\n\
         \x20   vk_beta_g2: VK_BETA_G2,\n\
         \x20   vk_gamme_g2: VK_GAMMA_G2,\n\
         \x20   vk_delta_g2: VK_DELTA_G2,\n\
         \x20   vk_ic: &VK_IC,\n\
         }};",
        vk.public_input_count()
    );
    s
}
