//! A live-cluster soak: the whole lifecycle against a real validator.
//!
//! Every assertion is a transaction that either landed or did not, and every
//! signature is printed so a third party can look it up. Nothing here is
//! simulated — the proof is generated by the host prover and verified by the
//! deployed program's own Groth16 syscall.

use crate::chain::Chain;
use anyhow::{anyhow, Context, Result};
use mirror_circuit::{generate_reproducible, prove, Keys, Witness};
use mirror_core::{Field, MerkleTree, Note};
use mirror_pool_program::{
    instruction::Instruction as MirrorIx,
    pda::{pool_address, spend_address, vault_address},
    processor::SELECTOR_TRANSFER,
};
use solana_keypair::Keypair;
use solana_program::{
    instruction::{AccountMeta, Instruction},
    pubkey::Pubkey,
};
use solana_signer::Signer;
use solana_transaction::Transaction;

const DENOMINATION: u64 = 20_000_001; // 0.02 SOL; a pool is per-denomination, so
                                      // this also picks out a fresh pool for the
                                      // evidence run.
const ENTRY_FEE: u64 = 0;
const K_FLOOR: u32 = 4;
const RELAY_FEE: u64 = 200_000;

/// One recorded step of the run.
pub struct Step {
    pub name: &'static str,
    pub signature: String,
    pub note: String,
}

pub struct Soak {
    client: Chain,
    program_id: Pubkey,
    payer: Keypair,
    pool: Pubkey,
    vault: Pubkey,
    pub steps: Vec<Step>,
    pub negatives: Vec<(String, String)>,
}

impl Soak {
    pub fn new(url: &str, program_id: Pubkey, payer: Keypair) -> Self {
        let (pool, _) = pool_address(&program_id, DENOMINATION);
        let (vault, _) = vault_address(&program_id, &pool);
        Soak {
            client: Chain::new(url),
            program_id,
            payer,
            pool,
            vault,
            steps: Vec::new(),
            negatives: Vec::new(),
        }
    }

    fn send(&self, ix: Instruction, signers: &[&Keypair]) -> Result<String> {
        let blockhash = self.client.latest_blockhash()?;
        let message = solana_message::Message::new(&[ix], Some(&signers[0].pubkey()));
        let tx = Transaction::new(signers, message, blockhash);
        self.client.send(&tx)
    }

    fn record(&mut self, name: &'static str, signature: String, note: String) {
        println!("  {name:<28} {signature}");
        self.steps.push(Step {
            name,
            signature,
            note,
        });
    }

    fn record_negative(&mut self, name: &str, err: String) {
        // Only the program's own error code matters here; the rest is noise.
        // Take only the hex code. The RPC embeds the error inside a JSON blob,
        // so splitting on whitespace drags the rest of the payload along and the
        // evidence table fills with noise instead of a code a reader can check.
        let code = err
            .split("custom program error: ")
            .nth(1)
            .map(|s| {
                s.chars()
                    .take_while(|c| c.is_ascii_hexdigit() || *c == 'x')
                    .collect::<String>()
            })
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| "(no custom code)".to_string());
        println!("  {name:<28} rejected with {code}");
        self.negatives.push((name.to_string(), code));
    }

    fn account_meta_pool(&self) -> Vec<AccountMeta> {
        vec![
            AccountMeta::new(self.payer.pubkey(), true),
            AccountMeta::new(self.pool, false),
            AccountMeta::new(self.vault, false),
            AccountMeta::new_readonly(solana_system_interface::program::ID, false),
        ]
    }

    /// Creates the pool, unless a previous run already did.
    pub fn init_pool(&mut self) -> Result<()> {
        if self.client.account_data(&self.pool)?.is_some() {
            println!("  pool already exists, reusing it");
            return Ok(());
        }
        let ix = Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::InitPool {
                denomination: DENOMINATION,
                entry_fee: ENTRY_FEE,
                k_floor: K_FLOOR,
            }
            .pack(),
            self.account_meta_pool(),
        );
        let payer = self.payer.insecure_clone();
        let sig = self.send(ix, &[&payer])?;
        self.record(
            "init_pool",
            sig,
            format!("denomination {DENOMINATION}, k_floor {K_FLOOR}"),
        );
        Ok(())
    }

    /// Deposits `count` notes and returns the host tree plus every note in it.
    ///
    /// Notes are persisted, not derived from a formula. The program stores only
    /// the accumulator frontier, so the host cannot reconstruct past leaves from
    /// the chain — and a formula only works if every deposit ever made used the
    /// same one. A rerun that guessed wrong would build a root the program has
    /// never held and every proof would fail with an unrelated error.
    pub fn deposit(
        &mut self,
        count: u64,
        ledger: &std::path::Path,
    ) -> Result<(MerkleTree, Vec<Note>)> {
        let denom_tag = Field::from_u64(DENOMINATION);
        let mut tree = MerkleTree::new().map_err(|e| anyhow!("{e}"))?;
        let mut notes = Vec::new();

        let mut secrets: Vec<(u64, u64)> = if ledger.exists() {
            serde_json::from_str(&std::fs::read_to_string(ledger)?)?
        } else {
            Vec::new()
        };
        let on_chain = self.leaf_count()? as usize;
        if secrets.len() != on_chain {
            return Err(anyhow!(
                "the note ledger holds {} notes but the pool has {on_chain} leaves. \
                 They must agree, or the host tree cannot match the program's root. \
                 Use a fresh denomination, or restore the ledger.",
                secrets.len()
            ));
        }
        for (k, r) in &secrets {
            let note = Note::new(Field::from_u64(*k), Field::from_u64(*r), denom_tag);
            tree.insert(note.commitment().map_err(|e| anyhow!("{e}"))?)
                .map_err(|e| anyhow!("{e}"))?;
            notes.push(note);
        }

        let base = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_secs();
        for j in 0..count {
            let k = base.wrapping_mul(1_000_003).wrapping_add(j * 7 + 1);
            let r = base.wrapping_mul(7_919).wrapping_add(j * 13 + 1);
            let note = Note::new(Field::from_u64(k), Field::from_u64(r), denom_tag);
            let commitment = note.commitment().map_err(|e| anyhow!("{e}"))?;
            let ix = Instruction::new_with_bytes(
                self.program_id,
                &MirrorIx::Deposit {
                    commitment: commitment.to_bytes(),
                }
                .pack(),
                self.account_meta_pool(),
            );
            let payer = self.payer.insecure_clone();
            let sig = self.send(ix, &[&payer])?;
            self.record("deposit", sig, format!("note {}", notes.len() + 1));
            tree.insert(commitment).map_err(|e| anyhow!("{e}"))?;
            notes.push(note);
            secrets.push((k, r));
            // Written after every deposit, so an interrupted run leaves a ledger
            // that still matches the chain.
            std::fs::write(ledger, serde_json::to_string(&secrets)?)?;
        }
        Ok((tree, notes))
    }

    fn leaf_count(&self) -> Result<u64> {
        let mut data = self
            .client
            .account_data(&self.pool)
            .context("reading the pool account")?
            .ok_or_else(|| anyhow!("the pool account does not exist"))?;
        let pool = mirror_pool_program::Pool::load(&mut data).map_err(|e| anyhow!("{e:?}"))?;
        Ok(pool.deposit_count())
    }

    /// Submits a spend for `index`, with a real proof, relay-signed.
    #[allow(clippy::too_many_arguments)]
    pub fn submit_spend(
        &mut self,
        keys: &Keys,
        tree: &MerkleTree,
        notes: &[Note],
        index: usize,
        beneficiary: &Pubkey,
        relay: &Keypair,
        label: &'static str,
    ) -> Result<(Pubkey, [u8; 32])> {
        use ark_std::rand::SeedableRng;
        let merkle_proof = tree.proof(index as u64).map_err(|e| anyhow!("{e}"))?;
        let binding = mirror_core::action_binding(
            SELECTOR_TRANSFER,
            &[0u8; 32],
            &beneficiary.to_bytes(),
            RELAY_FEE,
            &[],
        );
        let witness = Witness {
            note: notes[index],
            merkle_proof: &merkle_proof,
            root: tree.root().map_err(|e| anyhow!("{e}"))?,
            action_binding: binding,
        };
        let mut rng = ark_std::rand::rngs::StdRng::from_seed([index as u8 + 1; 32]);
        let proof = prove(keys, &witness, &mut rng).map_err(|e| anyhow!("{e}"))?;
        let nullifier = proof.public_inputs[1];
        let (spend_pda, _) = spend_address(&self.program_id, &self.pool, &nullifier);

        let ix = Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::SubmitSpend {
                proof_a: proof.proof_a,
                proof_b: proof.proof_b,
                proof_c: proof.proof_c,
                root: proof.public_inputs[0],
                nullifier,
                selector: SELECTOR_TRANSFER,
                target_program: [0u8; 32],
                beneficiary: beneficiary.to_bytes(),
                relay_fee: RELAY_FEE,
                action_accounts: 0,
                payload: Vec::new(),
            }
            .pack(),
            vec![
                AccountMeta::new(relay.pubkey(), true),
                AccountMeta::new(self.pool, false),
                AccountMeta::new(spend_pda, false),
                AccountMeta::new_readonly(solana_system_interface::program::ID, false),
            ],
        );
        let sig = self.send(ix, &[relay])?;
        self.record(label, sig, format!("note {index}, relay-signed"));
        Ok((spend_pda, nullifier))
    }

    /// Submits a spend expected to fail, recording the program's error code.
    #[allow(clippy::too_many_arguments)]
    pub fn expect_rejection(
        &mut self,
        name: &str,
        ix: Instruction,
        signers: &[&Keypair],
    ) -> Result<()> {
        match self.send(ix, signers) {
            Ok(sig) => Err(anyhow!("{name} was accepted: {sig}")),
            Err(e) => {
                self.record_negative(name, e.to_string());
                Ok(())
            }
        }
    }

    pub fn settle(&mut self, batch: &[(Pubkey, Pubkey, Pubkey)]) -> Result<()> {
        let mut metas = vec![
            AccountMeta::new(self.payer.pubkey(), true),
            AccountMeta::new(self.pool, false),
            AccountMeta::new(self.vault, false),
        ];
        for (spend, beneficiary, relay) in batch {
            metas.push(AccountMeta::new(*spend, false));
            metas.push(AccountMeta::new(*beneficiary, false));
            metas.push(AccountMeta::new(*relay, false));
        }
        let ix = Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::SettleEpoch {
                count: batch.len() as u8,
            }
            .pack(),
            metas,
        );
        let payer = self.payer.insecure_clone();
        let sig = self.send(ix, &[&payer])?;
        self.record("settle_epoch", sig, format!("{} spends", batch.len()));
        Ok(())
    }

    pub fn pool(&self) -> Pubkey {
        self.pool
    }
    pub fn vault(&self) -> Pubkey {
        self.vault
    }
    pub fn balance(&self, key: &Pubkey) -> Result<u64> {
        self.client.balance(key)
    }
    pub fn program_id(&self) -> Pubkey {
        self.program_id
    }
    pub fn spend_ix_for(
        &self,
        nullifier: [u8; 32],
        proof: &mirror_circuit::SolanaProof,
        beneficiary: &Pubkey,
        relay: &Pubkey,
        relay_fee: u64,
    ) -> Instruction {
        let (spend_pda, _) = spend_address(&self.program_id, &self.pool, &nullifier);
        Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::SubmitSpend {
                proof_a: proof.proof_a,
                proof_b: proof.proof_b,
                proof_c: proof.proof_c,
                root: proof.public_inputs[0],
                nullifier,
                selector: SELECTOR_TRANSFER,
                target_program: [0u8; 32],
                beneficiary: beneficiary.to_bytes(),
                relay_fee,
                action_accounts: 0,
                payload: Vec::new(),
            }
            .pack(),
            vec![
                AccountMeta::new(*relay, true),
                AccountMeta::new(self.pool, false),
                AccountMeta::new(spend_pda, false),
                AccountMeta::new_readonly(solana_system_interface::program::ID, false),
            ],
        )
    }
}

/// The setup keys, derived from the committed public seed.
pub fn keys() -> Result<Keys> {
    generate_reproducible(crate::DEV_SETUP_SEED.as_bytes()).map_err(|e| anyhow!("{e}"))
}

fn read_keypair(path: &str) -> Result<Keypair> {
    let expanded = if let Some(rest) = path.strip_prefix("~/") {
        format!("{}/{rest}", std::env::var("HOME")?)
    } else {
        path.to_string()
    };
    let bytes: Vec<u8> = serde_json::from_str(&std::fs::read_to_string(&expanded)?)?;
    Keypair::try_from(&bytes[..]).map_err(|e| anyhow!("reading {expanded}: {e}"))
}

/// The full lifecycle, on a live cluster, with every signature recorded.
pub fn run(program: &str, url: &str, keypair: &str, out: &std::path::Path) -> Result<()> {
    let program_id: Pubkey = program
        .parse()
        .map_err(|e| anyhow!("bad program id: {e}"))?;
    let payer = read_keypair(keypair)?;
    println!("program {program_id}");
    println!("payer   {}", payer.pubkey());
    println!("cluster {url}\n");

    let mut soak = Soak::new(url, program_id, payer.insecure_clone());
    println!("keys: deriving from the committed public seed (this takes a moment)");
    let keys = keys()?;

    println!("\npositive path:");
    soak.init_pool()?;
    let ledger = std::path::Path::new("data/soak-notes.json");
    let (tree, notes) = soak.deposit(K_FLOOR as u64, ledger)?;

    // Spend the notes this run deposited, not the earliest ones. A rerun
    // against a pool that already holds spent notes would otherwise replay a
    // burnt nullifier and stop.
    let first_fresh = notes.len() - K_FLOOR as usize;

    // One relay and one beneficiary per member: no member key appears anywhere.
    let mut batch = Vec::new();
    for i in first_fresh..first_fresh + K_FLOOR as usize {
        let beneficiary = Keypair::new().pubkey();
        let relay = payer.insecure_clone();
        let (spend, _) = soak.submit_spend(
            &keys,
            &tree,
            &notes,
            i,
            &beneficiary,
            &relay,
            "submit_spend",
        )?;
        batch.push((spend, beneficiary, relay.pubkey()));
    }

    let vault_before = soak.balance(&soak.vault())?;
    soak.settle(&batch)?;
    let vault_after = soak.balance(&soak.vault())?;
    println!(
        "  vault {vault_before} -> {vault_after} (paid out {})",
        vault_before.saturating_sub(vault_after)
    );

    println!("\nnegative path:");
    // A replayed proof: the nullifier record already exists.
    {
        use ark_std::rand::SeedableRng;
        let beneficiary = Keypair::new().pubkey();
        let merkle_proof = tree.proof(first_fresh as u64).map_err(|e| anyhow!("{e}"))?;
        let binding = mirror_core::action_binding(
            SELECTOR_TRANSFER,
            &[0u8; 32],
            &beneficiary.to_bytes(),
            RELAY_FEE,
            &[],
        );
        let witness = Witness {
            note: notes[first_fresh],
            merkle_proof: &merkle_proof,
            root: tree.root().map_err(|e| anyhow!("{e}"))?,
            action_binding: binding,
        };
        let mut rng = ark_std::rand::rngs::StdRng::from_seed([first_fresh as u8 + 1; 32]);
        let proof = prove(&keys, &witness, &mut rng).map_err(|e| anyhow!("{e}"))?;
        let ix = soak.spend_ix_for(
            proof.public_inputs[1],
            &proof,
            &beneficiary,
            &payer.pubkey(),
            RELAY_FEE,
        );
        soak.expect_rejection("replayed nullifier", ix, &[&payer])?;
    }

    write_proof(&soak, url, out)?;
    println!("\nwrote {}", out.display());
    Ok(())
}

fn write_proof(soak: &Soak, url: &str, out: &std::path::Path) -> Result<()> {
    let cluster = if url.contains("devnet") {
        "devnet"
    } else if url.contains("mainnet") {
        "mainnet-beta"
    } else {
        "custom"
    };
    let mut md = String::new();
    md.push_str("# Live-cluster evidence\n\n");
    md.push_str(
        "Every line here is a transaction that landed. Nothing is simulated: the \
         proof is produced by the host prover and verified by the deployed \
         program's own Groth16 syscall.\n\n",
    );
    md.push_str(&format!("- cluster: `{cluster}`\n"));
    md.push_str(&format!("- program: `{}`\n", soak.program_id()));
    md.push_str(&format!("- pool: `{}`\n", soak.pool()));
    md.push_str(&format!("- vault: `{}`\n\n", soak.vault()));

    md.push_str("## Flows\n\n| step | signature | note |\n|---|---|---|\n");
    for s in &soak.steps {
        md.push_str(&format!(
            "| {} | [`{}`](https://explorer.solana.com/tx/{}?cluster={cluster}) | {} |\n",
            s.name, s.signature, s.signature, s.note
        ));
    }

    md.push_str("\n## Rejections\n\n");
    md.push_str(
        "A negative case is only evidence if the program's own error code is what \
         rejected it. A bare runtime failure proves nothing about this program.\n\n",
    );
    md.push_str("| case | error code |\n|---|---|\n");
    for (name, code) in &soak.negatives {
        md.push_str(&format!("| {name} | `{code}` |\n"));
    }

    md.push_str("\n## Scope\n\n");
    md.push_str(
        "Devnet is devnet. This is a live-cluster functional proof, not a claim of \
         mainnet operation or of an anonymity crowd: the run is scripted by one \
         operator with a handful of notes. What it establishes is that the circuit, \
         the prover, the byte layout and the deployed program agree on a real \
         validator.\n",
    );
    std::fs::write(out, md)?;
    Ok(())
}
