//! A live-cluster soak: the whole lifecycle against a real validator.
//!
//! Every assertion is a transaction that either landed or did not, and every
//! signature is printed so a third party can look it up. Nothing here is
//! simulated — the proof is generated by the host prover and verified by the
//! deployed program's own Groth16 syscall.

use crate::chain::Chain;
use anyhow::{anyhow, Context, Result};
use mirror_circuit::{generate_reproducible, prove, Keys, Witness};
use mirror_core::{Field, MerkleTree, Note};
use mirror_pool_program::{
    instruction::Instruction as MirrorIx,
    pda::{pool_address, spend_address, vault_address},
    processor::{SELECTOR_INVOKE_SIGNED, SELECTOR_TRANSFER},
};
use solana_keypair::Keypair;
use solana_program::{
    instruction::{AccountMeta, Instruction},
    pubkey::Pubkey,
};
use solana_signer::Signer;
use solana_transaction::Transaction;

// A pool is unique per denomination, so this constant is also what selects the
// pool. Changing it starts a clean one, which is how the evidence run gets to
// record its own `init_pool` rather than reusing a pool an earlier run created
// and leaving the creation step undocumented.
const DENOMINATION: u64 = 20_000_019; // 0.02 SOL
const ENTRY_FEE: u64 = 0;
const K_FLOOR: u32 = 4;
/// Members in the evidence batch. Above `K_FLOOR` so the crowd rule is satisfied
/// by the crowd rather than by the timeout, and large enough to hold three
/// plain transfers beside the two actions the pool signs.
const BATCH: u64 = 5;
const RELAY_FEE: u64 = 200_000;

/// The SPL Memo program, at the same address on every cluster.
///
/// Used as the live-cluster CPI target for the same reason the end-to-end suite
/// uses it: it is somebody else's program, it is small, and it **refuses any
/// account handed to it that has not signed**. A memo whose only account is the
/// pool's vault therefore cannot succeed unless the pool really signed, which
/// makes the transaction itself the evidence rather than a claim about it.
const MEMO_PROGRAM: &str = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr";

/// What the member asks the pool to say on their behalf.
const MEMO_PAYLOAD: &[u8] = b"mirror-pool: signed by the pool, for a member";

/// The native Stake program.
const STAKE_PROGRAM: &str = "Stake11111111111111111111111111111111111111";
/// Still in `DelegateStake`'s account list, deprecated but not removed.
const STAKE_CONFIG: &str = "StakeConfig11111111111111111111111111111111";
const SYSVAR_CLOCK: &str = "SysvarC1ock11111111111111111111111111111111";
const SYSVAR_STAKE_HISTORY: &str = "SysvarStakeHistory1111111111111111111111111";
const SYSVAR_RENT: &str = "SysvarRent111111111111111111111111111111111";

/// `StakeInstruction::DelegateStake`, a bare u32 discriminant.
const DELEGATE_STAKE: [u8; 4] = [2, 0, 0, 0];

/// A devnet validator with a large active stake, so the delegation has somewhere
/// real to go.
const VOTE_ACCOUNT: &str = "2f9C9AU8nFRKUub8NHToNiZzcwmYiNeipVuP8akKgRVv";

/// `StakeStateV2` is 200 bytes whatever variant it holds.
const STAKE_ACCOUNT_LEN: usize = 200;

/// What the operator puts into the stake account before the pool delegates it.
///
/// Devnet's minimum delegation is 1 SOL and this pool's denomination is 0.02, so
/// the escrow of one member cannot reach the floor by itself — a pool whose
/// denomination cleared it would need five-plus SOL to fill a single batch. The
/// operator funds the account and the member's escrow is added to it; what the
/// *pool* supplies is the authority, which is the part being demonstrated.
const STAKE_FUNDING: u64 = 1_100_000_000;

/// One member's pending spend, as settlement needs to see it.
pub struct Settlement {
    pub spend: Pubkey,
    pub beneficiary: Pubkey,
    pub relay: Pubkey,
    /// The CPI target, when this member's action is a call rather than a
    /// transfer.
    pub target: Option<Pubkey>,
    /// The accounts that action takes, in the order the callee expects them.
    pub action_accounts: Vec<AccountMeta>,
}

/// One recorded step of the run.
pub struct Step {
    pub name: &'static str,
    pub signature: String,
    pub note: String,
}

/// What the vault actually held, so the solvency claim is checkable from this
/// artifact instead of from a sentence asserting it.
///
/// Saying "the vault closed to its rent-exempt minimum to the lamport" and then
/// publishing an evidence file containing only signatures asks a reader to take
/// the interesting part on trust. These are the numbers that sentence is about.
pub struct Accounting {
    pub denomination: u64,
    pub notes_settled: u64,
    pub relay_fee: u64,
    pub vault_before_settle: u64,
    pub vault_after_settle: u64,
    pub vault_rent_exempt_minimum: u64,
}

impl Accounting {
    /// What settlement was obliged to disburse: the full denomination for each
    /// note, which the relay fee is taken out of rather than added to.
    pub fn expected_payout(&self) -> u64 {
        self.denomination.saturating_mul(self.notes_settled)
    }

    pub fn observed_payout(&self) -> u64 {
        self.vault_before_settle
            .saturating_sub(self.vault_after_settle)
    }

    /// Whether the vault came to rest exactly on its rent-exempt floor, with
    /// every note paid and not one lamport more.
    pub fn closed_exactly(&self) -> bool {
        self.observed_payout() == self.expected_payout()
            && self.vault_after_settle == self.vault_rent_exempt_minimum
    }
}

pub struct Soak {
    client: Chain,
    program_id: Pubkey,
    payer: Keypair,
    pool: Pubkey,
    vault: Pubkey,
    pub steps: Vec<Step>,
    /// Case name, the program's own error code, and what the rejection proves.
    pub negatives: Vec<(String, String, String)>,
    pub accounting: Option<Accounting>,
    /// The callee's own log line naming the pool's vault as a signer.
    pub signed_action: Option<String>,
    /// The stake account the pool delegated, and the validator it now backs.
    pub delegation: Option<(Pubkey, Pubkey)>,
}

impl Soak {
    pub fn new(url: &str, program_id: Pubkey, payer: Keypair) -> Self {
        let (pool, _) = pool_address(&program_id, DENOMINATION);
        let (vault, _) = vault_address(&program_id, &pool);
        Soak {
            client: Chain::new(url),
            program_id,
            payer,
            pool,
            vault,
            steps: Vec::new(),
            negatives: Vec::new(),
            accounting: None,
            signed_action: None,
            delegation: None,
        }
    }

    fn send(&self, ix: Instruction, signers: &[&Keypair]) -> Result<String> {
        let blockhash = self.client.latest_blockhash()?;
        let message = solana_message::Message::new(&[ix], Some(&signers[0].pubkey()));
        let tx = Transaction::new(signers, message, blockhash);
        self.client.send(&tx)
    }

    fn record(&mut self, name: &'static str, signature: String, note: String) {
        println!("  {name:<28} {signature}");
        self.steps.push(Step {
            name,
            signature,
            note,
        });
    }

    fn record_negative(&mut self, name: &str, proves: &str, err: String) {
        // Only the program's own error code matters here; the rest is noise.
        // Take only the hex code. The RPC embeds the error inside a JSON blob,
        // so splitting on whitespace drags the rest of the payload along and the
        // evidence table fills with noise instead of a code a reader can check.
        let code = err
            .split("custom program error: ")
            .nth(1)
            .map(|s| {
                s.chars()
                    .take_while(|c| c.is_ascii_hexdigit() || *c == 'x')
                    .collect::<String>()
            })
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| "(no custom code)".to_string());
        println!("  {name:<28} rejected with {code}");
        self.negatives
            .push((name.to_string(), code, proves.to_string()));
    }

    fn account_meta_pool(&self) -> Vec<AccountMeta> {
        vec![
            AccountMeta::new(self.payer.pubkey(), true),
            AccountMeta::new(self.pool, false),
            AccountMeta::new(self.vault, false),
            AccountMeta::new_readonly(solana_system_interface::program::ID, false),
        ]
    }

    /// Creates the pool, unless a previous run already did.
    ///
    /// Reusing a pool is allowed only while it is empty. The accounting claim
    /// this run publishes — that the vault came to rest on its rent-exempt floor
    /// with a remainder of zero — is a statement about a pool whose every
    /// deposit this run also settles. A pool carrying notes from an earlier run
    /// cannot satisfy it, and finding that out at the assertion means having
    /// already spent the deposits to get there. It is checked before the money
    /// moves instead.
    pub fn init_pool(&mut self) -> Result<()> {
        if let Some(data) = self.client.account_data(&self.pool)? {
            let mut data = data;
            let pool = mirror_pool_program::Pool::load(&mut data)
                .map_err(|e| anyhow!("the account at the pool address is not a pool: {e:?}"))?;
            let outstanding = pool
                .outstanding_notes()
                .map_err(|e| anyhow!("reading the pool: {e:?}"))?;
            if outstanding > 0 {
                return Err(anyhow!(
                    "the pool for denomination {DENOMINATION} already holds {outstanding} \
                     unspent note(s), so this run cannot close its vault to the rent-exempt \
                     floor and the accounting table would be a different claim than the one \
                     it makes. Raise DENOMINATION in soak.rs for a clean pool — the note \
                     ledger is keyed by it, so a new denomination starts a new ledger too."
                ));
            }
            println!("  pool already exists and is empty, reusing it");
            return Ok(());
        }
        let ix = Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::InitPool {
                denomination: DENOMINATION,
                entry_fee: ENTRY_FEE,
                k_floor: K_FLOOR,
            }
            .pack(),
            self.account_meta_pool(),
        );
        let payer = self.payer.insecure_clone();
        let sig = self.send(ix, &[&payer])?;
        self.record(
            "init_pool",
            sig,
            format!("denomination {DENOMINATION}, k_floor {K_FLOOR}"),
        );
        Ok(())
    }

    /// Deposits `count` notes and returns the host tree plus every note in it.
    ///
    /// Notes are persisted, not derived from a formula. The program stores only
    /// the accumulator frontier, so the host cannot reconstruct past leaves from
    /// the chain — and a formula only works if every deposit ever made used the
    /// same one. A rerun that guessed wrong would build a root the program has
    /// never held and every proof would fail with an unrelated error.
    pub fn deposit(
        &mut self,
        count: u64,
        ledger: &std::path::Path,
    ) -> Result<(MerkleTree, Vec<Note>)> {
        let denom_tag = Field::from_u64(DENOMINATION);
        let mut tree = MerkleTree::new().map_err(|e| anyhow!("{e}"))?;
        let mut notes = Vec::new();

        let mut secrets: Vec<(u64, u64)> = if ledger.exists() {
            serde_json::from_str(&std::fs::read_to_string(ledger)?)?
        } else {
            Vec::new()
        };
        let on_chain = self.leaf_count()? as usize;
        if secrets.len() != on_chain {
            return Err(anyhow!(
                "the note ledger holds {} notes but the pool has {on_chain} leaves. \
                 They must agree, or the host tree cannot match the program's root. \
                 Use a fresh denomination, or restore the ledger.",
                secrets.len()
            ));
        }
        for (k, r) in &secrets {
            let note = Note::new(Field::from_u64(*k), Field::from_u64(*r), denom_tag);
            tree.insert(note.commitment().map_err(|e| anyhow!("{e}"))?)
                .map_err(|e| anyhow!("{e}"))?;
            notes.push(note);
        }

        let base = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_secs();
        for j in 0..count {
            let k = base.wrapping_mul(1_000_003).wrapping_add(j * 7 + 1);
            let r = base.wrapping_mul(7_919).wrapping_add(j * 13 + 1);
            let note = Note::new(Field::from_u64(k), Field::from_u64(r), denom_tag);
            let commitment = note.commitment().map_err(|e| anyhow!("{e}"))?;
            let ix = Instruction::new_with_bytes(
                self.program_id,
                &MirrorIx::Deposit {
                    commitment: commitment.to_bytes(),
                }
                .pack(),
                self.account_meta_pool(),
            );
            let payer = self.payer.insecure_clone();
            let sig = self.send(ix, &[&payer])?;
            self.record("deposit", sig, format!("note {}", notes.len() + 1));
            tree.insert(commitment).map_err(|e| anyhow!("{e}"))?;
            notes.push(note);
            secrets.push((k, r));
            // Written after every deposit, so an interrupted run leaves a ledger
            // that still matches the chain.
            std::fs::write(ledger, serde_json::to_string(&secrets)?)?;
        }
        Ok((tree, notes))
    }

    fn leaf_count(&self) -> Result<u64> {
        let mut data = self
            .client
            .account_data(&self.pool)
            .context("reading the pool account")?
            .ok_or_else(|| anyhow!("the pool account does not exist"))?;
        let pool = mirror_pool_program::Pool::load(&mut data).map_err(|e| anyhow!("{e:?}"))?;
        Ok(pool.deposit_count())
    }

    /// Submits a spend for `index`, with a real proof, relay-signed.
    #[allow(clippy::too_many_arguments)]
    pub fn submit_spend(
        &mut self,
        keys: &Keys,
        tree: &MerkleTree,
        notes: &[Note],
        index: usize,
        beneficiary: &Pubkey,
        relay: &Keypair,
        label: &'static str,
    ) -> Result<(Pubkey, [u8; 32])> {
        use ark_std::rand::SeedableRng;
        let merkle_proof = tree.proof(index as u64).map_err(|e| anyhow!("{e}"))?;
        let binding = mirror_core::action_binding(
            SELECTOR_TRANSFER,
            &[0u8; 32],
            &beneficiary.to_bytes(),
            RELAY_FEE,
            0,
            &[],
        );
        let witness = Witness {
            note: notes[index],
            merkle_proof: &merkle_proof,
            root: tree.root().map_err(|e| anyhow!("{e}"))?,
            action_binding: binding,
        };
        let mut rng = ark_std::rand::rngs::StdRng::from_seed([index as u8 + 1; 32]);
        let proof = prove(keys, &witness, &mut rng).map_err(|e| anyhow!("{e}"))?;
        let nullifier = proof.public_inputs[1];
        let (spend_pda, _) = spend_address(&self.program_id, &self.pool, &nullifier);

        let ix = Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::SubmitSpend {
                proof_a: proof.proof_a,
                proof_b: proof.proof_b,
                proof_c: proof.proof_c,
                root: proof.public_inputs[0],
                nullifier,
                selector: SELECTOR_TRANSFER,
                target_program: [0u8; 32],
                beneficiary: beneficiary.to_bytes(),
                relay_fee: RELAY_FEE,
                action_accounts: 0,
                payload: Vec::new(),
            }
            .pack(),
            vec![
                AccountMeta::new(relay.pubkey(), true),
                AccountMeta::new(self.pool, false),
                AccountMeta::new(spend_pda, false),
                AccountMeta::new_readonly(solana_system_interface::program::ID, false),
            ],
        );
        let sig = self.send(ix, &[relay])?;
        self.record(label, sig, format!("note {index}, relay-signed"));
        Ok((spend_pda, nullifier))
    }

    /// Submits a spend whose action is a **CPI the pool signs**, not a transfer.
    ///
    /// The action declares one account, and settlement will fill that slot with
    /// the vault. The count is inside the action binding, so a settler cannot
    /// add or drop a slot; the selector is inside it too, so the pool's signature
    /// is something the member proved they wanted and not something settlement
    /// can help itself to.
    #[allow(clippy::too_many_arguments)]
    pub fn submit_signed_action(
        &mut self,
        keys: &Keys,
        tree: &MerkleTree,
        notes: &[Note],
        index: usize,
        beneficiary: &Pubkey,
        relay: &Keypair,
        target: &Pubkey,
    ) -> Result<(Pubkey, [u8; 32])> {
        use ark_std::rand::SeedableRng;
        let merkle_proof = tree.proof(index as u64).map_err(|e| anyhow!("{e}"))?;
        let binding = mirror_core::action_binding(
            SELECTOR_INVOKE_SIGNED,
            &target.to_bytes(),
            &beneficiary.to_bytes(),
            RELAY_FEE,
            1,
            MEMO_PAYLOAD,
        );
        let witness = Witness {
            note: notes[index],
            merkle_proof: &merkle_proof,
            root: tree.root().map_err(|e| anyhow!("{e}"))?,
            action_binding: binding,
        };
        let mut rng = ark_std::rand::rngs::StdRng::from_seed([index as u8 + 1; 32]);
        let proof = prove(keys, &witness, &mut rng).map_err(|e| anyhow!("{e}"))?;
        let nullifier = proof.public_inputs[1];
        let (spend_pda, _) = spend_address(&self.program_id, &self.pool, &nullifier);

        let ix = Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::SubmitSpend {
                proof_a: proof.proof_a,
                proof_b: proof.proof_b,
                proof_c: proof.proof_c,
                root: proof.public_inputs[0],
                nullifier,
                selector: SELECTOR_INVOKE_SIGNED,
                target_program: target.to_bytes(),
                beneficiary: beneficiary.to_bytes(),
                relay_fee: RELAY_FEE,
                action_accounts: 1,
                payload: MEMO_PAYLOAD.to_vec(),
            }
            .pack(),
            vec![
                AccountMeta::new(relay.pubkey(), true),
                AccountMeta::new(self.pool, false),
                AccountMeta::new(spend_pda, false),
                AccountMeta::new_readonly(solana_system_interface::program::ID, false),
            ],
        );
        let sig = self.send(ix, &[relay])?;
        self.record(
            "submit_spend",
            sig,
            format!("note {index}, relay-signed, action: pool-signed CPI to SPL Memo"),
        );
        Ok((spend_pda, nullifier))
    }

    /// Creates a stake account whose **staker** is the pool's vault.
    ///
    /// The withdraw authority is deliberately *not* the vault, and that is the
    /// threat model applied rather than restated: the pool's signature is
    /// available to every member, so an authority held by the vault is an
    /// authority every member holds. Staking is safe to delegate that way
    /// because the worst a member can do with it is delegate somebody else's
    /// stake to a different validator. Withdrawal is not, so it stays with the
    /// operator.
    pub fn create_stake_account(&mut self) -> Result<Pubkey> {
        let stake = Keypair::new();
        let stake_program: Pubkey = STAKE_PROGRAM
            .parse()
            .map_err(|e| anyhow!("stake id: {e}"))?;
        let rent_sysvar: Pubkey = SYSVAR_RENT.parse().map_err(|e| anyhow!("rent id: {e}"))?;

        let create = solana_system_interface::instruction::create_account(
            &self.payer.pubkey(),
            &stake.pubkey(),
            STAKE_FUNDING,
            STAKE_ACCOUNT_LEN as u64,
            &stake_program,
        );

        // StakeInstruction::Initialize { Authorized, Lockup }, bincode: a u32
        // discriminant then the two authorities and a zero lockup.
        let mut data = 0u32.to_le_bytes().to_vec();
        data.extend_from_slice(self.vault.as_ref()); // staker
        data.extend_from_slice(&self.payer.pubkey().to_bytes()); // withdrawer
        data.extend_from_slice(&0i64.to_le_bytes()); // lockup.unix_timestamp
        data.extend_from_slice(&0u64.to_le_bytes()); // lockup.epoch
        data.extend_from_slice(&[0u8; 32]); // lockup.custodian
        let initialise = Instruction::new_with_bytes(
            stake_program,
            &data,
            vec![
                AccountMeta::new(stake.pubkey(), false),
                AccountMeta::new_readonly(rent_sysvar, false),
            ],
        );

        let blockhash = self.client.latest_blockhash()?;
        let message =
            solana_message::Message::new(&[create, initialise], Some(&self.payer.pubkey()));
        let payer = self.payer.insecure_clone();
        let tx = Transaction::new(&[&payer, &stake], message, blockhash);
        let sig = self.client.send(&tx)?;
        self.record(
            "create stake account",
            sig,
            format!(
                "{} lamports, staker = the pool's vault, withdrawer = the operator",
                STAKE_FUNDING
            ),
        );
        Ok(stake.pubkey())
    }

    /// The action list `DelegateStake` expects, in the callee's own order.
    ///
    /// Taken from what the `solana` CLI builds rather than from memory: the
    /// authority sits in the last slot, and the deprecated config account is
    /// still in the list. Getting this order wrong is not a compile error and
    /// not a clear runtime one either — the stake program would read the config
    /// account as the authority and report a missing signature.
    fn delegate_accounts(&self, stake: &Pubkey) -> Result<Vec<AccountMeta>> {
        let parse = |s: &str| -> Result<Pubkey> { s.parse().map_err(|e| anyhow!("{s}: {e}")) };
        Ok(vec![
            AccountMeta::new(*stake, false),
            AccountMeta::new_readonly(parse(VOTE_ACCOUNT)?, false),
            AccountMeta::new_readonly(parse(SYSVAR_CLOCK)?, false),
            AccountMeta::new_readonly(parse(SYSVAR_STAKE_HISTORY)?, false),
            AccountMeta::new_readonly(parse(STAKE_CONFIG)?, false),
            AccountMeta::new_readonly(self.vault, false),
        ])
    }

    /// Submits a spend whose action is a real stake delegation, authorised by
    /// the pool.
    #[allow(clippy::too_many_arguments)]
    pub fn submit_stake_delegation(
        &mut self,
        keys: &Keys,
        tree: &MerkleTree,
        notes: &[Note],
        index: usize,
        stake: &Pubkey,
        relay: &Keypair,
    ) -> Result<(Pubkey, [u8; 32])> {
        use ark_std::rand::SeedableRng;
        let stake_program: Pubkey = STAKE_PROGRAM
            .parse()
            .map_err(|e| anyhow!("stake id: {e}"))?;
        let merkle_proof = tree.proof(index as u64).map_err(|e| anyhow!("{e}"))?;
        // The stake account is the beneficiary, so the member's escrow lands in
        // the stake they authorised rather than beside it.
        let binding = mirror_core::action_binding(
            SELECTOR_INVOKE_SIGNED,
            &stake_program.to_bytes(),
            &stake.to_bytes(),
            RELAY_FEE,
            6,
            &DELEGATE_STAKE,
        );
        let witness = Witness {
            note: notes[index],
            merkle_proof: &merkle_proof,
            root: tree.root().map_err(|e| anyhow!("{e}"))?,
            action_binding: binding,
        };
        let mut rng = ark_std::rand::rngs::StdRng::from_seed([index as u8 + 1; 32]);
        let proof = prove(keys, &witness, &mut rng).map_err(|e| anyhow!("{e}"))?;
        let nullifier = proof.public_inputs[1];
        let (spend_pda, _) = spend_address(&self.program_id, &self.pool, &nullifier);

        let ix = Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::SubmitSpend {
                proof_a: proof.proof_a,
                proof_b: proof.proof_b,
                proof_c: proof.proof_c,
                root: proof.public_inputs[0],
                nullifier,
                selector: SELECTOR_INVOKE_SIGNED,
                target_program: stake_program.to_bytes(),
                beneficiary: stake.to_bytes(),
                relay_fee: RELAY_FEE,
                action_accounts: 6,
                payload: DELEGATE_STAKE.to_vec(),
            }
            .pack(),
            vec![
                AccountMeta::new(relay.pubkey(), true),
                AccountMeta::new(self.pool, false),
                AccountMeta::new(spend_pda, false),
                AccountMeta::new_readonly(solana_system_interface::program::ID, false),
            ],
        );
        let sig = self.send(ix, &[relay])?;
        self.record(
            "submit_spend",
            sig,
            format!("note {index}, relay-signed, action: pool-signed stake delegation"),
        );
        Ok((spend_pda, nullifier))
    }

    /// Reads the stake account back and reports which validator it now backs.
    ///
    /// `StakeStateV2` is a bincode enum: a u32 discriminant, then `Meta` (8 bytes
    /// of rent reserve, two 32-byte authorities, a 48-byte lockup), then
    /// `Delegation`, whose first field is the vote account. Variant 2 is `Stake`,
    /// which an account only reaches by being delegated — an initialised but
    /// undelegated account is variant 1, so the discriminant alone distinguishes
    /// "the instruction landed" from "the delegation took".
    pub fn confirm_delegated(&mut self, stake: &Pubkey) -> Result<()> {
        let data = self
            .client
            .account_data(stake)?
            .ok_or_else(|| anyhow!("the stake account {stake} vanished"))?;
        if data.len() < 156 {
            return Err(anyhow!(
                "the stake account is {} bytes, too short to be a stake state",
                data.len()
            ));
        }
        let discriminant = u32::from_le_bytes([data[0], data[1], data[2], data[3]]);
        if discriminant != 2 {
            return Err(anyhow!(
                "the stake account is in state {discriminant}, not Stake(2): the \
                 delegation did not take"
            ));
        }
        let voter = Pubkey::new_from_array(
            data[124..156]
                .try_into()
                .map_err(|_| anyhow!("reading the vote account"))?,
        );
        println!("  stake account delegated to {voter}");
        self.delegation = Some((*stake, voter));
        Ok(())
    }

    /// Submits a spend expected to fail, recording the program's error code.
    #[allow(clippy::too_many_arguments)]
    pub fn expect_rejection(
        &mut self,
        name: &str,
        proves: &str,
        ix: Instruction,
        signers: &[&Keypair],
    ) -> Result<()> {
        match self.send(ix, signers) {
            Ok(sig) => Err(anyhow!("{name} was accepted: {sig}")),
            Err(e) => {
                self.record_negative(name, proves, e.to_string());
                Ok(())
            }
        }
    }

    /// Reads the callee's own logs to confirm the pool signed the inner call.
    ///
    /// The settle signature proves a transaction landed. It says nothing about
    /// who signed the instruction the pool made *inside* it, and that is the
    /// claim worth checking, so this asks the cluster for the logs and looks for
    /// what SPL Memo says. Memo names every signer it was given and refuses any
    /// account that has not signed, so its own words are the evidence — and if
    /// they are absent the run fails here rather than publishing the claim.
    pub fn confirm_pool_signed(&mut self, signature: &str) -> Result<()> {
        let logs = self.client.transaction_logs(signature)?;
        let vault = self.vault.to_string();
        let line = logs
            .iter()
            .find(|l| l.contains("Signed by") && l.contains(&vault))
            .ok_or_else(|| {
                anyhow!(
                    "settlement landed but SPL Memo did not report the pool's vault \
                     ({vault}) as a signer, so the pool did not actually sign. Logs:\n{}",
                    logs.join("\n")
                )
            })?
            .clone();
        println!("  the callee's own log: {}", line.trim());
        self.signed_action = Some(line);
        Ok(())
    }

    /// Settles a batch. An entry carrying a target program is a CPI action, and
    /// the vault follows it as that action's one account.
    pub fn settle(&mut self, batch: &[Settlement]) -> Result<String> {
        let mut metas = vec![
            AccountMeta::new(self.payer.pubkey(), true),
            AccountMeta::new(self.pool, false),
            AccountMeta::new(self.vault, false),
        ];
        let mut actions = 0usize;
        for entry in batch {
            metas.push(AccountMeta::new(entry.spend, false));
            metas.push(AccountMeta::new(entry.beneficiary, false));
            metas.push(AccountMeta::new(entry.relay, false));
            if let Some(target) = entry.target {
                actions += 1;
                metas.push(AccountMeta::new_readonly(target, false));
                // The action's own accounts, in the callee's order. Where one of
                // them is the vault it reaches the callee as a *signer* — the
                // program sets that flag itself, from seeds no settler holds,
                // which is why the meta here says otherwise.
                metas.extend(entry.action_accounts.iter().cloned());
            }
        }
        let ix = Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::SettleEpoch {
                count: batch.len() as u8,
            }
            .pack(),
            metas,
        );
        let payer = self.payer.insecure_clone();
        let sig = self.send(ix, &[&payer])?;
        let note = if actions == 0 {
            format!("{} spends", batch.len())
        } else {
            format!(
                "{} spends in one transaction, {actions} of them a CPI the pool signed",
                batch.len()
            )
        };
        self.record("settle_epoch", sig.clone(), note);
        Ok(sig)
    }

    pub fn pool(&self) -> Pubkey {
        self.pool
    }
    pub fn vault(&self) -> Pubkey {
        self.vault
    }
    pub fn balance(&self, key: &Pubkey) -> Result<u64> {
        self.client.balance(key)
    }

    pub fn rent_exempt_minimum(&self, space: usize) -> Result<u64> {
        self.client.rent_exempt_minimum(space)
    }
    pub fn program_id(&self) -> Pubkey {
        self.program_id
    }
    pub fn spend_ix_for(
        &self,
        nullifier: [u8; 32],
        proof: &mirror_circuit::SolanaProof,
        beneficiary: &Pubkey,
        relay: &Pubkey,
        relay_fee: u64,
    ) -> Instruction {
        let (spend_pda, _) = spend_address(&self.program_id, &self.pool, &nullifier);
        Instruction::new_with_bytes(
            self.program_id,
            &MirrorIx::SubmitSpend {
                proof_a: proof.proof_a,
                proof_b: proof.proof_b,
                proof_c: proof.proof_c,
                root: proof.public_inputs[0],
                nullifier,
                selector: SELECTOR_TRANSFER,
                target_program: [0u8; 32],
                beneficiary: beneficiary.to_bytes(),
                relay_fee,
                action_accounts: 0,
                payload: Vec::new(),
            }
            .pack(),
            vec![
                AccountMeta::new(*relay, true),
                AccountMeta::new(self.pool, false),
                AccountMeta::new(spend_pda, false),
                AccountMeta::new_readonly(solana_system_interface::program::ID, false),
            ],
        )
    }
}

/// The setup keys, derived from the committed public seed.
pub fn keys() -> Result<Keys> {
    generate_reproducible(crate::DEV_SETUP_SEED.as_bytes()).map_err(|e| anyhow!("{e}"))
}

pub fn read_keypair(path: &str) -> Result<Keypair> {
    let expanded = if let Some(rest) = path.strip_prefix("~/") {
        format!("{}/{rest}", std::env::var("HOME")?)
    } else {
        path.to_string()
    };
    let bytes: Vec<u8> = serde_json::from_str(&std::fs::read_to_string(&expanded)?)?;
    Keypair::try_from(&bytes[..]).map_err(|e| anyhow!("reading {expanded}: {e}"))
}

/// Proves membership of one note, bound to one beneficiary and one relay fee.
///
/// Kept separate so a negative case can prove an honest statement and then send
/// a *different* one. That is the whole shape of the redirect attack: the proof
/// is genuine, and what the relay changes is the instruction around it.
fn proof_for_note(
    keys: &Keys,
    tree: &MerkleTree,
    notes: &[Note],
    index: usize,
    beneficiary: &Pubkey,
    relay_fee: u64,
) -> Result<mirror_circuit::SolanaProof> {
    use ark_std::rand::SeedableRng;
    let merkle_proof = tree.proof(index as u64).map_err(|e| anyhow!("{e}"))?;
    let binding = mirror_core::action_binding(
        SELECTOR_TRANSFER,
        &[0u8; 32],
        &beneficiary.to_bytes(),
        relay_fee,
        0,
        &[],
    );
    let witness = Witness {
        note: notes[index],
        merkle_proof: &merkle_proof,
        root: tree.root().map_err(|e| anyhow!("{e}"))?,
        action_binding: binding,
    };
    let mut rng = ark_std::rand::rngs::StdRng::from_seed([index as u8 + 1; 32]);
    prove(keys, &witness, &mut rng).map_err(|e| anyhow!("{e}"))
}

/// The full lifecycle, on a live cluster, with every signature recorded.
pub fn run(program: &str, url: &str, keypair: &str, out: &std::path::Path) -> Result<()> {
    let program_id: Pubkey = program
        .parse()
        .map_err(|e| anyhow!("bad program id: {e}"))?;
    let payer = read_keypair(keypair)?;
    println!("program {program_id}");
    println!("payer   {}", payer.pubkey());
    println!("cluster {url}\n");

    let mut soak = Soak::new(url, program_id, payer.insecure_clone());
    println!("keys: deriving from the committed public seed (this takes a moment)");
    let keys = keys()?;

    println!("\npositive path:");
    soak.init_pool()?;

    // The ledger is scoped to the denomination because the pool is. `deposit`
    // refuses to run when the ledger and the chain disagree on how many leaves
    // exist, and tells you to use a fresh denomination — advice that a single
    // shared ledger file would make impossible to follow, since the fresh pool
    // starts empty and the old notes are still in the file.
    let ledger_path = format!("data/soak-notes-{DENOMINATION}.json");
    let ledger = std::path::Path::new(&ledger_path);
    let (tree, notes) = soak.deposit(BATCH, ledger)?;

    // Spend the notes this run deposited, not the earliest ones. A rerun
    // against a pool that already holds spent notes would otherwise replay a
    // burnt nullifier and stop.
    let first_fresh = notes.len() - BATCH as usize;

    // One relay and one beneficiary per member: no member key appears anywhere.
    //
    // The last member asks for something different from the rest — a CPI the
    // pool signs — and it settles in the *same* transaction as the transfers.
    // That is the design's own claim about itself: an observer sees one
    // timestamp, one signer and a batch of actions, with nothing separating the
    // member who staked from the members who merely moved value.
    let memo: Pubkey = MEMO_PROGRAM.parse().map_err(|e| anyhow!("memo id: {e}"))?;
    let stake_program: Pubkey = STAKE_PROGRAM
        .parse()
        .map_err(|e| anyhow!("stake id: {e}"))?;

    // The stake account exists before any member asks for anything, and who
    // created it is public. What the pool supplies is the authority to delegate
    // it, and which member asked for that is what the anonymity set hides.
    let stake = soak.create_stake_account()?;

    let memo_note = first_fresh + BATCH as usize - 2;
    let stake_note = first_fresh + BATCH as usize - 1;
    let mut batch = Vec::new();
    for i in first_fresh..first_fresh + BATCH as usize {
        let relay = payer.insecure_clone();
        let entry = if i == stake_note {
            let (spend, _) =
                soak.submit_stake_delegation(&keys, &tree, &notes, i, &stake, &relay)?;
            Settlement {
                spend,
                // The stake account is the beneficiary, so this member's escrow
                // ends up inside the stake they authorised.
                beneficiary: stake,
                relay: relay.pubkey(),
                target: Some(stake_program),
                action_accounts: soak.delegate_accounts(&stake)?,
            }
        } else if i == memo_note {
            let beneficiary = Keypair::new().pubkey();
            let (spend, _) =
                soak.submit_signed_action(&keys, &tree, &notes, i, &beneficiary, &relay, &memo)?;
            Settlement {
                spend,
                beneficiary,
                relay: relay.pubkey(),
                target: Some(memo),
                action_accounts: vec![AccountMeta::new(soak.vault(), false)],
            }
        } else {
            let beneficiary = Keypair::new().pubkey();
            let (spend, _) = soak.submit_spend(
                &keys,
                &tree,
                &notes,
                i,
                &beneficiary,
                &relay,
                "submit_spend",
            )?;
            Settlement {
                spend,
                beneficiary,
                relay: relay.pubkey(),
                target: None,
                action_accounts: Vec::new(),
            }
        };
        batch.push(entry);
    }

    let vault_before = soak.balance(&soak.vault())?;
    let settle_sig = soak.settle(&batch)?;
    soak.confirm_pool_signed(&settle_sig)?;
    soak.confirm_delegated(&stake)?;
    let vault_after = soak.balance(&soak.vault())?;
    // The vault carries no data, so its floor is the rent-exempt minimum for a
    // zero-byte account — asked of the cluster rather than assumed.
    let vault_floor = soak.rent_exempt_minimum(0)?;
    let accounting = Accounting {
        denomination: DENOMINATION,
        notes_settled: BATCH,
        relay_fee: RELAY_FEE,
        vault_before_settle: vault_before,
        vault_after_settle: vault_after,
        vault_rent_exempt_minimum: vault_floor,
    };
    println!(
        "  vault {vault_before} -> {vault_after} (paid out {}, expected {}, floor {vault_floor})",
        accounting.observed_payout(),
        accounting.expected_payout(),
    );
    // Assert it here rather than only reporting it. A soak that prints an
    // unexpected number and exits zero is a soak that proves nothing.
    if !accounting.closed_exactly() {
        return Err(anyhow!(
            "vault did not close cleanly: paid out {} against an expected {}, \
             and came to rest at {} against a rent-exempt floor of {vault_floor}",
            accounting.observed_payout(),
            accounting.expected_payout(),
            accounting.vault_after_settle,
        ));
    }
    println!("  vault closed to its rent-exempt floor exactly");
    soak.accounting = Some(accounting);

    println!("\nnegative path:");

    // One more note, deposited only now. Two of the three negatives below need
    // a *live* note: a rejection against an already-spent one proves the replay
    // guard fired first and says nothing about the check under test. It is
    // deposited after settlement so the accounting above still describes a
    // vault that emptied to its floor rather than one holding a spare.
    let (tree, notes) = soak.deposit(1, ledger)?;
    let spare = notes.len() - 1;

    // A replayed proof: honest in every respect, against a note already spent.
    {
        let beneficiary = Keypair::new().pubkey();
        let proof = proof_for_note(&keys, &tree, &notes, first_fresh, &beneficiary, RELAY_FEE)?;
        let ix = soak.spend_ix_for(
            proof.public_inputs[1],
            &proof,
            &beneficiary,
            &payer.pubkey(),
            RELAY_FEE,
        );
        soak.expect_rejection(
            "replayed nullifier",
            "a nullifier is spent once, ever -- not once per epoch",
            ix,
            &[&payer],
        )?;
    }

    // A relay redirecting a payout. The proof is genuine and the note is live;
    // the relay simply names a different beneficiary in the instruction. The
    // binding is recomputed on-chain from what the instruction says, so it no
    // longer matches the one inside the proof and the pairing fails.
    {
        let member_chose = Keypair::new().pubkey();
        let relay_prefers = Keypair::new().pubkey();
        let proof = proof_for_note(&keys, &tree, &notes, spare, &member_chose, RELAY_FEE)?;
        let ix = soak.spend_ix_for(
            proof.public_inputs[1],
            &proof,
            &relay_prefers,
            &payer.pubkey(),
            RELAY_FEE,
        );
        soak.expect_rejection(
            "redirected beneficiary",
            "a relay cannot send a member's payout somewhere the member did not choose",
            ix,
            &[&payer],
        )?;
    }

    // The other half of the same claim: a relay re-pricing its own fee. Same
    // live note, same genuine proof, and the only change is the fee the
    // instruction declares.
    {
        let beneficiary = Keypair::new().pubkey();
        let proof = proof_for_note(&keys, &tree, &notes, spare, &beneficiary, RELAY_FEE)?;
        let ix = soak.spend_ix_for(
            proof.public_inputs[1],
            &proof,
            &beneficiary,
            &payer.pubkey(),
            RELAY_FEE * 10,
        );
        soak.expect_rejection(
            "inflated relay fee",
            "a relay cannot re-price the work after the member authorised it",
            ix,
            &[&payer],
        )?;
    }

    write_proof(&soak, url, out)?;
    println!("\nwrote {}", out.display());
    Ok(())
}

fn write_proof(soak: &Soak, url: &str, out: &std::path::Path) -> Result<()> {
    let cluster = if url.contains("devnet") {
        "devnet"
    } else if url.contains("mainnet") {
        "mainnet-beta"
    } else {
        "custom"
    };
    let mut md = String::new();
    md.push_str("# Live-cluster evidence\n\n");
    md.push_str(
        "Every line here is a transaction that landed. Nothing is simulated: the \
         proof is produced by the host prover and verified by the deployed \
         program's own Groth16 syscall.\n\n",
    );
    md.push_str(&format!("- cluster: `{cluster}`\n"));
    md.push_str(&format!("- program: `{}`\n", soak.program_id()));
    md.push_str(&format!("- pool: `{}`\n", soak.pool()));
    md.push_str(&format!("- vault: `{}`\n\n", soak.vault()));

    md.push_str("## Flows\n\n| step | signature | note |\n|---|---|---|\n");
    for s in &soak.steps {
        md.push_str(&format!(
            "| {} | [`{}`](https://explorer.solana.com/tx/{}?cluster={cluster}) | {} |\n",
            s.name, s.signature, s.signature, s.note
        ));
    }

    if let Some(a) = &soak.accounting {
        md.push_str("\n## Vault accounting\n\n");
        md.push_str(
            "The accounting invariant is a statement about the vault's lamports, so \
             here are the lamports. The vault holds escrow and carries no data, which \
             is what makes its floor the rent-exempt minimum for a zero-byte account \
             — read from the cluster during the run, not assumed.\n\n",
        );
        md.push_str("| quantity | lamports |\n|---|---|\n");
        md.push_str(&format!("| denomination | {} |\n", a.denomination));
        md.push_str(&format!("| notes settled | {} |\n", a.notes_settled));
        md.push_str(&format!(
            "| relay fee (taken out of the denomination, not added) | {} |\n",
            a.relay_fee
        ));
        md.push_str(&format!(
            "| vault before settlement | {} |\n",
            a.vault_before_settle
        ));
        md.push_str(&format!(
            "| vault after settlement | {} |\n",
            a.vault_after_settle
        ));
        md.push_str(&format!(
            "| rent-exempt minimum, 0 bytes | {} |\n",
            a.vault_rent_exempt_minimum
        ));
        md.push_str(&format!("| **paid out** | **{}** |\n", a.observed_payout()));
        md.push_str(&format!(
            "| **owed** (denomination × notes) | **{}** |\n\n",
            a.expected_payout()
        ));
        md.push_str(&format!(
            "Paid out equals owed, and the vault came to rest on its floor with a \
             remainder of {} lamports. The soak asserts both and fails the run \
             otherwise, so this table cannot record a discrepancy and still exit \
             successfully.\n",
            a.vault_after_settle
                .saturating_sub(a.vault_rent_exempt_minimum)
        ));
    }

    if let Some(line) = &soak.signed_action {
        md.push_str("\n## The pool signed an action, and the callee said so\n\n");
        md.push_str(
            "The settlement above carried four spends, and one of them was not a transfer: \
             the pool invoked SPL Memo as that member's **authority**, in the same \
             transaction as the other three. That is the capability a stake delegation or a \
             governance vote needs and a payment does not.\n\n",
        );
        md.push_str(
            "A signature only proves the transaction landed. It says nothing about who \
             signed the instruction the pool made *inside* it, so the evidence has to come \
             from the callee. SPL Memo refuses any account handed to it that has not signed, \
             and names the ones that did:\n\n",
        );
        md.push_str(&format!("```\n{}\n```\n\n", line.trim()));
        md.push_str(&format!(
            "That is the pool's vault, `{}`, which has no private key — it signed through \
             seeds only the program holds. The soak reads this line back from the cluster \
             and fails the run if it is absent, so this section cannot appear without the \
             callee having said it.\n",
            soak.vault()
        ));
    }

    if let Some((stake, voter)) = &soak.delegation {
        md.push_str("\n## The pool delegated stake, as a member's authority\n\n");
        md.push_str(&format!(
            "The same settlement carried a second signed action, and this one is the case \
             the design exists for: a **real stake delegation**. Stake account \
             [`{stake}`](https://explorer.solana.com/address/{stake}?cluster=devnet) is now \
             delegated to validator \
             [`{voter}`](https://explorer.solana.com/address/{voter}?cluster=devnet).\n\n"
        ));
        md.push_str(
            "`DelegateStake` requires the **staker authority** to sign. No member can be that \
             authority without appearing on chain and undoing the point, so the pool is, and \
             the pool signed. The account state is read back after settlement: a stake \
             account only reaches the `Stake` variant by being delegated — an initialised but \
             undelegated one is a different variant — so the check distinguishes \"the \
             instruction landed\" from \"the delegation took\", and the validator's key is \
             read out of the account rather than assumed from what was requested.\n\n",
        );
        md.push_str(
            "**The withdraw authority is deliberately not the pool.** The pool's signature is \
             available to every member, so an authority the vault holds is an authority every \
             member holds. Delegation is safe on those terms — the worst a member can do is \
             re-delegate to another validator. Withdrawal is not, and it stays with the \
             operator. That is `docs/THREAT_MODEL.md` applied rather than repeated.\n\n",
        );
        md.push_str(&format!(
            "What is hidden here is precisely one thing: **which member asked**. The stake \
             account, the validator, the amount and the timing are all public, and the \
             anonymity set is the {BATCH} members who settled together. What an observer \
             cannot recover is which of them authorised this delegation rather than one of \
             the plain transfers beside it.\n"
        ));
    }

    md.push_str("\n## Rejections\n\n");
    md.push_str(
        "A negative case is only evidence if the program's own error code is what \
         rejected it. A bare runtime failure proves nothing about this program.\n\n",
    );
    md.push_str("| case | error code | what the rejection establishes |\n|---|---|---|\n");
    for (name, code, proves) in &soak.negatives {
        md.push_str(&format!("| {name} | `{code}` | {proves} |\n"));
    }
    md.push_str(
        "\nThe last two attack a note that is still live, deposited after settlement \
         precisely so that they would have to. Against an already-spent note the \
         replay guard fires first and the rejection would say nothing about the \
         check under test — which is how a negative case comes to pass for the \
         wrong reason.\n",
    );

    md.push_str("\n## Scope\n\n");
    md.push_str(
        "Devnet is devnet. This is a live-cluster functional proof, not a claim of \
         mainnet operation or of an anonymity crowd: the run is scripted by one \
         operator with a handful of notes. What it establishes is that the circuit, \
         the prover, the byte layout and the deployed program agree on a real \
         validator.\n",
    );
    std::fs::write(out, md)?;
    Ok(())
}
